@startuml Diagramme de classes logiciel - projet GL
skinparam ranksep 50
skinparam nodesep 40
left to right direction

' =============================
' === MODELE (Model) ===
' =============================
package "Model" {

enum Univers

class Personnage {
  -String nom
  -String profession
  -String naissanceDate
  -String image
  -Univers univers
  -Biographie biographie
  +void setProfession(String newProfession)
  +void supprimer()
}

class Joueur {
  -String nom
  +Personnage creerPersonnage(String nom, String naissanceDate, String profession, Biographie bioInitiale)
  +Partie proposerPartie(String titre, Univers univers, String resume)
}

class MeneurJeu {
  +void accepterPartie(Partie p)
  +void accepterPersonnage(Personnage personnage)
  +void validerEpisode(Episode e)
}

class Partie {
  -boolean jouee
  -List<Personnage> personnages
  +void valider()
  +void ajouterPersonnage(Personnage p)
  +void supprimerPersonnage(Personnage p)
  +void jouer()
}

class Aventure
class Biographie {
  -String titre
  -List<Episode> episodes
  +void ajouterEpisode(Episode e)
}

class Episode {
  -String titre
  -List<Paragraphe> paragraphes
  +void ajouterParagraphe(Paragraphe p)
  +void valider()
}

class Paragraphe {
  -String titre
  -boolean isPrivate
  +void rendrePublique()
}

' === Patterns ===

' Gere la creation des personnages et toutes les verifications necessaire (notammrnt sur l'univers)
class PersonnageFactory {
  -static instance : PersonnageFactory
  +static PersonnageFactory getInstance()
  +Personnage creerPersonnage(String nom, String date, String profession, Biographie bio)
}

' Fabrique les parties et les aventures
class PartieFactory {
  -staic instance : PartieFactory
  +static PartieFactory getInstance()
  +Partie creerPartie(String titre, Univers univers, String resume)
}

' interface ValidationStrategy {
'   +boolean valider(Object element)
' }
' class ValidationEpisodeStrategy implements ValidationStrategy
' class ValidationPartieStrategy implements ValidationStrategy

abstract class Sujet {
  +attache(Observateur o)
  +detache(Observateur o)
  +informe()
}

interface Observateur {
  +miseAJour()
}

' Singleton

class GestionnaireJeu {
  -static instance : GestionnaireJeu
  -List<Partie> parties
  +static GestionnaireJeu getInstance()
  +void ajouterPartie(Partie p)
}

' Associations modèle
' Joueur "1" --> "0..*" Partie : propose >
' Partie "1" --> "1" Aventure
' Personnage "1" --> "1" Biographie
' Biographie "1" --> "0..*" Episode
' Episode "1" --> "0..*" Paragraphe
' Personnage --> Univers
' MeneurJeu --> Partie
' Partie --> Personnage
diamond diamond1
diamond diamond2

Joueur "1" -- diamond1
Partie "1" -- diamond1
Personnage "1" -- diamond1

MeneurJeu "1" -- diamond2
Partie "1" -- diamond2
Personnage "1"-- diamond2

Episode --* Biographie
Paragraphe --* Episode

Episode --> "0,*" Aventure : est lié
Partie --> Aventure : se rapporte

Personnage "1,*" --> "1,*" Aventure
Personnage "1" --> "1" Biographie 
Partie .. Univers
Personnage .. Univers

GestionnaireJeu "1" -->"1,*" Partie

PersonnageFactory "1" --> "1,*" Personnage
PartieFactory "1" --> "1,*" Partie

' ValidationStrategy <|-- ValidationEpisodeStrategy
' ValidationStrategy <|-- ValidationPartieStrategy

Sujet <|-- Partie
Sujet <|-- Episode
Sujet <|-- Paragraphe
Sujet <|-- Joueur

Observateur <|.. VuePartie
Observateur <|.. VueEpisode
Observateur <|.. VueParagrahe
Observateur <|.. VueJoueur

}

' =============================
' === VUE (View) ===
' =============================
package "View" {
  class VuePartie {
    +afficherPartie(Partie p)
  }
  class VueBiographie {
    +afficherProfil(Joueur j)
  }
  class VueEpisode {

  }
  class VueParagraphe {

  }
  class VueConnexion {
    
  }
  class VuePersonnage {
    +afficherDetails(Personnage p)
  }
  class VueJoueur {

  }
}

' =============================
' === CONTROLEUR (Controller) ===
' =============================
package "Controller" {
  class ControleurPartie {
    +void creerPartie()
    +void validerPartie()
  }
  class ControleurJoueur {
    +void creerPersonnage()
    +void proposerPartie()
  }
}

' Relations MVC
ControleurPartie --> Partie
ControleurJoueur --> Joueur
VuePartie --> ControleurPartie
VueJoueur --> ControleurJoueur
VuePersonnage --> ControleurJoueur

Partie -[#blue,dashed]-> VuePartie : <<Observer>>
Joueur -[#blue,dashed]-> VueJoueur : <<Observer>>

@enduml
