@startuml
actor Joueur

Joueur -> Vue_joueur: command_proposer(args...)
Vue_joueur -> Controleur_partie: command_proposer(args...)
activate Controleur_partie
Controleur_partie -> Controleur_partie : Proposer_partie(titre, univers, resume initiale, date, lieu)
create Partie

Controleur_partie-> Partie: new(args...)
deactivate Controleur_partie
Partie --> Controleur_partie: Partie P
Controleur_partie--> Vue_joueur: Partie P



@enduml
