@startuml
actor Joueur
actor MeneurJeu

Joueur --> Vue_joueur: command_create(args...)
Vue_joueur -> Controleur_joueur: creer_personnage(nom,date de naissance,profession,portrait,biographie)
create Personnage
Controleur_joueur -> Personnage: new(non,date de naissance,profession,portrait,biographie)

Personnage --> Controleur_joueur: Personnage p
Controleur_joueur --> Vue_joueur: Personnage p
Joueur --> Vue_joueur: command_ajouter(args..)

Vue_joueur -> Controleur_partie: ajouterPersonnage(p,args..)
Controleur_partie --> Vue_joueur: demande_confirmation
'Vue_joueur->MeneurJeu: demande_confirmation
MeneurJeu --> Vue_joueur: commmand_confirmation(args...)
Vue_joueur --> Controleur_partie: confirmation
Controleur_partie -> Personnage: setMeneurJeu(args...)
Controleur_partie -> Partie : ajouter_personnage(p,args...)
'Partie-> Controleur_partie: demande_confirmation()
@enduml